using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EndpointPlatform.Infrastructure.Persistence;

/// <summary>
/// Rewrites the whole relational model to snake_case.
/// </summary>
/// <remarks>
/// <para>
/// PostgreSQL folds unquoted identifiers to lower case, so a CLR name such as
/// <c>OrganizationId</c> would otherwise become the quoted, shift-key-requiring
/// <c>"OrganizationId"</c>. Every hand-written query, migration and psql session
/// then has to quote it exactly. snake_case keeps SQL written by hand identical to
/// SQL generated by EF.
/// </para>
/// <para>
/// Implemented here rather than by taking a dependency on EFCore.NamingConventions:
/// it is thirty lines, it removes a package that must be version-matched to EF on
/// every upgrade, and the behaviour is pinned by
/// <c>SnakeCaseNamingConventionTests</c>.
/// </para>
/// </remarks>
internal static class SnakeCaseNamingConvention
{
    public static void ApplyTo(ModelBuilder modelBuilder)
    {
        ArgumentNullException.ThrowIfNull(modelBuilder);

        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            // Skip owned types that share their owner's table; the owner already renamed it.
            var tableName = entityType.GetTableName();
            if (tableName is not null)
            {
                entityType.SetTableName(ToSnakeCase(tableName));
            }

            foreach (var property in entityType.GetProperties())
            {
                var storeObject = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
                var columnName = storeObject is { } so
                    ? property.GetColumnName(so) ?? property.Name
                    : property.Name;

                property.SetColumnName(ToSnakeCase(columnName));
            }

            foreach (var key in entityType.GetKeys())
            {
                var name = key.GetName();
                if (name is not null)
                {
                    key.SetName(ToSnakeCase(name));
                }
            }

            foreach (var foreignKey in entityType.GetForeignKeys())
            {
                var name = foreignKey.GetConstraintName();
                if (name is not null)
                {
                    foreignKey.SetConstraintName(ToSnakeCase(name));
                }
            }

            foreach (var index in entityType.GetIndexes())
            {
                var name = index.GetDatabaseName();
                if (name is not null)
                {
                    index.SetDatabaseName(ToSnakeCase(name));
                }
            }
        }
    }

    /// <summary>
    /// Converts PascalCase / camelCase to snake_case, treating an acronym run as a
    /// single word so <c>SourceIP</c> becomes <c>source_ip</c> rather than
    /// <c>source_i_p</c>. Input that is already snake_case is returned unchanged.
    /// </summary>
    internal static string ToSnakeCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        var builder = new StringBuilder(name.Length + 8);

        for (var i = 0; i < name.Length; i++)
        {
            var current = name[i];

            if (current == '_')
            {
                builder.Append('_');
                continue;
            }

            if (char.IsUpper(current))
            {
                var isFirst = i == 0;
                var previousIsLowerOrDigit = !isFirst && (char.IsLower(name[i - 1]) || char.IsDigit(name[i - 1]));
                var nextIsLower = i + 1 < name.Length && char.IsLower(name[i + 1]);
                var previousIsUpper = !isFirst && char.IsUpper(name[i - 1]);

                // Boundary before "Id" in "OrganizationId", and before "Name" in "IPName".
                if (!isFirst && (previousIsLowerOrDigit || (previousIsUpper && nextIsLower)) && builder[^1] != '_')
                {
                    builder.Append('_');
                }

                builder.Append(char.ToLowerInvariant(current));
                continue;
            }

            builder.Append(current);
        }

        return builder.ToString();
    }
}
