// <auto-generated />
using System;
using System.Net;
using EndpointPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EndpointPlatform.Migrations.Schema
{
    [DbContext(typeof(EndpointPlatformDbContext))]
    [Migration("20260818000414_DeviceLocalAccounts")]
    partial class DeviceLocalAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("endpoint_platform")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EndpointPlatform.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplay")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_display");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DeviceDisplay")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_display");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("NewState")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousState")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_state");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("required_permission");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<string>("TargetDisplay")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_display");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_log_entries_correlation_id");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entries_actor_id_occurred_at");

                    b.HasIndex("DeviceId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entries_device_id_occurred_at");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entries_failures")
                        .HasFilter("result <> 'Success'");

                    b.HasIndex("OrganizationId", "Action", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_log_entries_organization_id_action_occurred_at");

                    b.ToTable("audit_log_entries", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("EnrolledWithTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_with_token_id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("InventoryCollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inventory_collected_at");

                    b.Property<DateTimeOffset?>("InventoryRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inventory_requested_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LoggedOnUser")
                        .HasColumnType("text")
                        .HasColumnName("logged_on_user");

                    b.Property<string>("MachineIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("machine_identifier");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operating_system");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("EnrolledWithTokenId")
                        .HasDatabaseName("ix_devices_enrolled_with_token_id");

                    b.HasIndex("OrganizationId", "Hostname")
                        .HasDatabaseName("ix_devices_organization_id_hostname");

                    b.HasIndex("OrganizationId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_devices_organization_id_last_seen_at");

                    b.HasIndex("OrganizationId", "MachineIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_organization_id_machine_identifier");

                    b.ToTable("devices", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceHardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<int?>("CpuLogicalProcessors")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_logical_processors");

                    b.Property<string>("CpuName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cpu_name");

                    b.Property<int?>("CpuPhysicalCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_physical_cores");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("DisksJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("disks_json");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<long?>("TotalMemoryBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_memory_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_hardware");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_hardware_device_id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_device_hardware_serial_number");

                    b.ToTable("device_hardware", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceLocalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_count");

                    b.Property<string>("MembersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("members_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("character varying(184)")
                        .HasColumnName("sid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_local_groups");

                    b.HasIndex("DeviceId", "Sid")
                        .IsUnique()
                        .HasDatabaseName("ix_device_local_groups_device_id_sid");

                    b.ToTable("device_local_groups", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceLocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsLocalAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local_administrator");

                    b.Property<DateTimeOffset?>("LastLogon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<bool>("PasswordExpires")
                        .HasColumnType("boolean")
                        .HasColumnName("password_expires");

                    b.Property<bool>("PasswordRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("password_required");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("character varying(184)")
                        .HasColumnName("sid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_local_users");

                    b.HasIndex("IsLocalAdministrator")
                        .HasDatabaseName("ix_device_local_users_is_local_administrator")
                        .HasFilter("is_local_administrator");

                    b.HasIndex("DeviceId", "Sid")
                        .IsUnique()
                        .HasDatabaseName("ix_device_local_users_device_id_sid");

                    b.ToTable("device_local_users", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceNetworkInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("IpAddressesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ip_addresses_json");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_up");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(23)
                        .HasColumnType("character varying(23)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_network_interfaces");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_network_interfaces_device_id");

                    b.HasIndex("MacAddress")
                        .HasDatabaseName("ix_device_network_interfaces_mac_address");

                    b.ToTable("device_network_interfaces", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Enrollment.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("key_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agent_credentials");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_credentials_device_id_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_credentials_key_id");

                    b.ToTable("agent_credentials", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Enrollment.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByDisplay")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("created_by_display");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_enrollment_tokens");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollment_tokens_secret_hash");

                    b.HasIndex("OrganizationId", "ExpiresAt")
                        .HasDatabaseName("ix_enrollment_tokens_organization_id_expires_at");

                    b.ToTable("enrollment_tokens", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.AdminSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecurityStampSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp_snapshot");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_admin_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_admin_sessions_expires_at");

                    b.HasIndex("PlatformUserId")
                        .HasDatabaseName("ix_admin_sessions_platform_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_sessions_token_hash");

                    b.ToTable("admin_sessions", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("is_high_risk");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_count");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_account");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_updated_at");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_users");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_platform_users_status");

                    b.HasIndex("OrganizationId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_users_organization_id_normalized_email");

                    b.ToTable("platform_users", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.PlatformUserRole", b =>
                {
                    b.Property<Guid>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("PlatformUserId", "RoleId")
                        .HasName("pk_platform_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_platform_user_roles_role_id");

                    b.ToTable("platform_user_roles", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_key_builtin")
                        .HasFilter("organization_id IS NULL");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_organization_id_key")
                        .HasFilter("organization_id IS NOT NULL");

                    b.ToTable("roles", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "endpoint_platform");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_organizations_organization_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.Device", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Enrollment.EnrollmentToken", null)
                        .WithMany()
                        .HasForeignKey("EnrolledWithTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_enrollment_tokens_enrolled_with_token_id");

                    b.HasOne("EndpointPlatform.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_organizations_organization_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceHardware", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Devices.Device", null)
                        .WithOne()
                        .HasForeignKey("EndpointPlatform.Domain.Devices.DeviceHardware", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_hardware_devices_device_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceLocalGroup", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_local_groups_devices_device_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceLocalUser", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_local_users_devices_device_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Devices.DeviceNetworkInterface", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_network_interfaces_devices_device_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Enrollment.AgentCredential", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_credentials_devices_device_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Enrollment.EnrollmentToken", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_tokens_organizations_organization_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.AdminSession", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.PlatformUser", "PlatformUser")
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_sessions_platform_users_platform_user_id");

                    b.Navigation("PlatformUser");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.PlatformUser", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platform_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.PlatformUserRole", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.PlatformUser", "PlatformUser")
                        .WithMany("Roles")
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_user_roles_platform_users_platform_user_id");

                    b.HasOne("EndpointPlatform.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_user_roles_roles_role_id");

                    b.Navigation("PlatformUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.Role", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_roles_organizations_organization_id");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("EndpointPlatform.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("EndpointPlatform.Domain.Identity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.PlatformUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("EndpointPlatform.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
