<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EndpointPlatform.Infrastructure.Tests</RootNamespace>
    <AssemblyName>EndpointPlatform.Infrastructure.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\EndpointPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Migrations\EndpointPlatform.Migrations.csproj" />
  </ItemGroup>

</Project>
